// <auto-generated />
using System;
using Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(QLNSDbContext))]
    partial class QLNSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.DAOs.Bangcong", b =>
                {
                    b.Property<Guid>("Idbc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDBC");

                    b.Property<int?>("Giora")
                        .HasColumnType("int")
                        .HasColumnName("GIORA");

                    b.Property<int?>("Giovao")
                        .HasColumnType("int")
                        .HasColumnName("GIOVAO");

                    b.Property<Guid?>("LDloaicong")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lDLOAICONG");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<int?>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("NAM");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int")
                        .HasColumnName("NGAY");

                    b.Property<int?>("Phutra")
                        .HasColumnType("int")
                        .HasColumnName("PHUTRA");

                    b.Property<int?>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("THANG");

                    b.HasKey("Idbc");

                    b.HasIndex("LDloaicong");

                    b.HasIndex("Manv");

                    b.ToTable("BANGCONG", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Bangluong", b =>
                {
                    b.Property<Guid>("Idbangluong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDBANGLUONG");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<double?>("Luongcoban")
                        .HasColumnType("float")
                        .HasColumnName("LUONGCOBAN");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.HasKey("Idbangluong");

                    b.HasIndex("Manv");

                    b.ToTable("BANGLUONG", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Baohiem", b =>
                {
                    b.Property<Guid>("Idbh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDBH");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<DateTime?>("Ngaycap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYCAP");

                    b.Property<string>("Noicap")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NOICAP");

                    b.Property<string>("Noidkikhambenh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOIDKIKHAMBENH");

                    b.Property<string>("Sobh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SOBH");

                    b.HasKey("Idbh");

                    b.HasIndex("Manv");

                    b.ToTable("BAOHIEM", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Chucvu", b =>
                {
                    b.Property<Guid>("Idcv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDCV");

                    b.Property<string>("Tenchucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHUCVU");

                    b.HasKey("Idcv");

                    b.ToTable("CHUCVU", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Hopdong", b =>
                {
                    b.Property<int>("Sohd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SOHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sohd"));

                    b.Property<double?>("Hesoluong")
                        .HasColumnType("float")
                        .HasColumnName("HESOLUONG");

                    b.Property<int?>("Lanky")
                        .HasColumnType("int")
                        .HasColumnName("LANKY");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<DateTime?>("Ngaybatdau")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime?>("Ngayketthuc")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<DateTime?>("Ngayky")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYKY");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOIDUNG");

                    b.Property<string>("Thoihan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("THOIHAN");

                    b.HasKey("Sohd");

                    b.HasIndex("Manv");

                    b.ToTable("HOPDONG", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Khenthuongkyluat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int?>("Loai")
                        .HasColumnType("int")
                        .HasColumnName("LOAI");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAY");

                    b.Property<string>("Noidung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOIDUNG");

                    b.Property<int?>("Soktlt")
                        .HasColumnType("int")
                        .HasColumnName("SOKTLT");

                    b.HasKey("Id");

                    b.HasIndex("Manv");

                    b.ToTable("KHENTHUONGKYLUAT", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Loaica", b =>
                {
                    b.Property<Guid>("Idloaica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDLOAICA");

                    b.Property<double?>("Heso")
                        .HasColumnType("float")
                        .HasColumnName("HESO");

                    b.Property<string>("Tenloaica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAICA");

                    b.HasKey("Idloaica");

                    b.ToTable("LOAICA", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Loaicong", b =>
                {
                    b.Property<Guid>("Idloaicong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDLOAICONG");

                    b.Property<double?>("Heso")
                        .HasColumnType("float")
                        .HasColumnName("HESO");

                    b.Property<string>("Tenloaicong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAICONG");

                    b.HasKey("Idloaicong");

                    b.ToTable("LOAICONG", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Nhanvien", b =>
                {
                    b.Property<Guid>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<string>("Cccd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CCCD");

                    b.Property<string>("Diachi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DIACHI");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<byte[]>("Hinhanh")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<Guid?>("Idbp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDBP");

                    b.Property<Guid?>("Idcv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDCV");

                    b.Property<Guid?>("Idpb")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPB");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SDT");

                    b.HasKey("Manv");

                    b.HasIndex("Idcv");

                    b.HasIndex("Idpb");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Nhanvienphucap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<Guid?>("Idpc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPC");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAY");

                    b.Property<string>("Noidung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NOIDUNG");

                    b.Property<double?>("Sotien")
                        .HasColumnType("float")
                        .HasColumnName("SOTIEN");

                    b.HasKey("Id");

                    b.HasIndex("Idpc");

                    b.HasIndex("Manv");

                    b.ToTable("NHANVIENPHUCAP", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Phongban", b =>
                {
                    b.Property<Guid>("Idpb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPB");

                    b.Property<string>("Tenpb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENPB");

                    b.HasKey("Idpb");

                    b.ToTable("PHONGBAN", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Phucap", b =>
                {
                    b.Property<Guid>("Idpc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPC");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Sotien")
                        .HasColumnType("float")
                        .HasColumnName("SOTIEN");

                    b.Property<string>("Tenpc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENPC");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Idpc");

                    b.ToTable("PHUCAP", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Tangca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid?>("Idloaica")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDLOAICA");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<int?>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("NAM");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int")
                        .HasColumnName("NGAY");

                    b.Property<double?>("Sogio")
                        .HasColumnType("float")
                        .HasColumnName("SOGIO");

                    b.Property<int?>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("THANG");

                    b.HasKey("Id");

                    b.HasIndex("Idloaica");

                    b.HasIndex("Manv");

                    b.ToTable("TANGCA", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Ungluong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid?>("Manv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MANV");

                    b.Property<int?>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("NAM");

                    b.Property<int?>("Ngay")
                        .HasColumnType("int")
                        .HasColumnName("NGAY");

                    b.Property<double?>("Sotien")
                        .HasColumnType("float")
                        .HasColumnName("SOTIEN");

                    b.Property<int?>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("THANG");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.HasIndex("Manv");

                    b.ToTable("UNGLUONG", (string)null);
                });

            modelBuilder.Entity("Entities.DAOs.Bangcong", b =>
                {
                    b.HasOne("Entities.DAOs.Loaicong", "LDloaicongNavigation")
                        .WithMany("Bangcongs")
                        .HasForeignKey("LDloaicong")
                        .HasConstraintName("FK_BANGCONG_LOAICONG");

                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Bangcongs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_BANGCONG_NHANVIEN");

                    b.Navigation("LDloaicongNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Bangluong", b =>
                {
                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Bangluongs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_BANGLUONG_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Baohiem", b =>
                {
                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Baohiems")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_BAOHIEM_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Hopdong", b =>
                {
                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Hopdongs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_HOPDONG_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Khenthuongkyluat", b =>
                {
                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Khenthuongkyluats")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_KHENTHUONGKYLUAT_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Nhanvien", b =>
                {
                    b.HasOne("Entities.DAOs.Chucvu", "IdcvNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("Idcv")
                        .HasConstraintName("FK_NHANVIEN_CHUCVU");

                    b.HasOne("Entities.DAOs.Phongban", "IdpbNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("Idpb")
                        .HasConstraintName("FK_NHANVIEN_PHONGBAN1");

                    b.Navigation("IdcvNavigation");

                    b.Navigation("IdpbNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Nhanvienphucap", b =>
                {
                    b.HasOne("Entities.DAOs.Phucap", "IdpcNavigation")
                        .WithMany("Nhanvienphucaps")
                        .HasForeignKey("Idpc")
                        .HasConstraintName("FK_NHANVIENPHUCAP_PHUCAP");

                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Nhanvienphucaps")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_NHANVIENPHUCAP_NHANVIEN");

                    b.Navigation("IdpcNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Tangca", b =>
                {
                    b.HasOne("Entities.DAOs.Loaica", "IdloaicaNavigation")
                        .WithMany("Tangcas")
                        .HasForeignKey("Idloaica")
                        .HasConstraintName("FK_TANGCA_LOAICA");

                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Tangcas")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_TANGCA_NHANVIEN");

                    b.Navigation("IdloaicaNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Ungluong", b =>
                {
                    b.HasOne("Entities.DAOs.Nhanvien", "ManvNavigation")
                        .WithMany("Ungluongs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_UNGLUONG_NHANVIEN");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Entities.DAOs.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("Entities.DAOs.Loaica", b =>
                {
                    b.Navigation("Tangcas");
                });

            modelBuilder.Entity("Entities.DAOs.Loaicong", b =>
                {
                    b.Navigation("Bangcongs");
                });

            modelBuilder.Entity("Entities.DAOs.Nhanvien", b =>
                {
                    b.Navigation("Bangcongs");

                    b.Navigation("Bangluongs");

                    b.Navigation("Baohiems");

                    b.Navigation("Hopdongs");

                    b.Navigation("Khenthuongkyluats");

                    b.Navigation("Nhanvienphucaps");

                    b.Navigation("Tangcas");

                    b.Navigation("Ungluongs");
                });

            modelBuilder.Entity("Entities.DAOs.Phongban", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("Entities.DAOs.Phucap", b =>
                {
                    b.Navigation("Nhanvienphucaps");
                });
#pragma warning restore 612, 618
        }
    }
}
